#!/bin/sh
opkg remove enigma2-plugin-extensions-freecccam
curl http://download1581.mediafire.com/oki3iw06rbhg/x8zc4k106siqfu2/enigma2-plugin-extensions-freecccam_5.2_all.ipk -Lko /tmp/enigma2-plugin-extensions-freecccam_5.2_all.ipk
opkg --force-overwrite install /tmp/enigma2-plugin-extensions-freecccam_5.2_all.ipk
opkg install --force-reinstall /tmp/enigma2-plugin-extensions-freecccam_5.2_all.ipk
rm -rf /tmp/enigma2-plugin-extensions-freecccam_5.2_all.ipk > /dev/null
echo  'YouTube KANALIMA ABONE OLARAK TAKIP EDEBILIRSINIZ'
echo  'https://www.youtube.com/c/ReMyTr'
sleep 2
killall -9 enigma2