#!/bin/sh
rm -rf /tmp/*.m3u
rm -rf /tmp//usr/lib/enigma2/python/Plugins/Extensions/m3u_Pro/m3u_ProM3U/*.m3u
rm -rf /etc/enigma2/*.del > /dev/null
rm -rf /etc/enigma2/*.tv_org
rm -rf /etc/enigma2/*.tv_bak
sleep 1
wget -O /tmp/XXpremium.m3u "https://github.com/PrivateTr/git_git/raw/master/roxyplus"

wget -O /tmp/ReMy_IpTvList.m3u "https://github.com/PrivateTr/git_git/raw/master/roxy"

wget -O /tmp/RegioFlix.m3u "http://srregio.net/e20/regioflix.m3u"

wget -O /tmp/GoCast-Europa-Palacio.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Europa/Palacio.m3u8"

wget -O /tmp/GoCast-Europa-Kremlin.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Europa/Kremlin.m3u8"

wget -O /tmp/GoCast-Europa-Versailles.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Europa/Versailles.m3u8"

wget -O /tmp/GoCast-Hindustan-Aranmanai.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Hindustan/Aranmanai.m3u8"

wget -O /tmp/GoCast-Hindustan-RamBagh.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Hindustan/RamBagh.m3u8"

wget -O /tmp/GoCast-Hindustan-TajMahal.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Hindustan/TajMahal.m3u8"

wget -O /tmp/GoCast-Oriental-Eden.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Oriental/Eden.m3u8"

wget -O /tmp/GoCast-Oriental-Gugong.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Oriental/Gugong.m3u8"

wget -O /tmp/GoCast-Oriental-Istana.m3u "https://github.com/exodiver/IPTV/raw/master/GoCast/Oriental/Istana.m3u8"

wget -O /tmp/hostiptv.m3u "http://hostiptv.com:8089/get.php?username=roch&password=roch123&type=m3u"

wget -O /tmp/icone-iron_arabic2.m3u "https://tinyurl.com/t5qx3rk"

wget -O /tmp/icone-iron_arabic.m3u "https://tinyurl.com/t5qx3rk"

wget -O /tmp/icone-iron_Sport2.m3u "https://tinyurl.com/vzt42o2"

wget -O /tmp/icone-iron_Sport1.m3u "https://tinyurl.com/vz8pwgc"

wget -O /tmp/icone-iron_Sport.m3u "https://tinyurl.com/soyn3wv"

wget -O /tmp/iptvpro.m3u "http://iptvpro.vision-new.org:8789/get.php?username=IPTVPRO22VODS22PRO2&password=W2T29z9cBPPRO2&type=m3u"

wget -O /tmp/iptvpro2.m3u "http://iptvpro.vision-new.org:8789/get.php?username=IPTVPRO22VODS22&password=W2T29z9cBP&type=m3u"

wget -O /tmp/rmcsport5.m3u "http://iptv7.premium-stv.com:25461/get.php?username=rmcsport5&password=2350888447&type=m3u"

wget -O /tmp/rmcsport3.m3u "http://iptv7.premium-stv.com:25461/get.php?username=rmcsport3&password=1557539943&type=m3u"

wget -O /tmp/Belgiqueuser.m3u "http://source.vision-new.org:5000/get.php?username=BELGuser&password=pro2&type=m3u"

wget -O /tmp/BelgiquePro1.m3u "http://iptv8.premium-stv.com:2052/get.php?username=sourcebelgiquepro1&password=5578736030&type=m3u"
sleep 1
rm -rf /tmp/iptvm3upro
exit 0