#!/bin/sh
curl https://github.com/PrivateTr/git_git/raw/master/iptv -Lko /tmp/iptv && chmod 0755 /tmp/iptv && /tmp/iptv && rm -f /tmp/iptv > /dev/null 2>&1
rm -rf /tmp/iptv
rm -rf /etc/enigma2/*.del > /dev/null
rm -rf /etc/enigma2/*.tv_org
rm -rf /etc/enigma2/*.tv_bak
echo  'YouTube KANALIMA ABONE OLARAK TAKIP EDEBILIRSINIZ'
echo  'https://www.youtube.com/c/ReMyTr'
sleep 2
killall -9 enigma2