#!/bin/sh
opkg update
curl https://github.com/PrivateTr/git_git/raw/master/enigma2-plugin-softcams-remy-openatv-softcampanel_V2.1_all.ipk -Lko /tmp/enigma2-plugin-softcams-remy-openatv-softcampanel_V2.1_all.ipk
sleep 1
opkg --force-overwrite install /tmp/enigma2-plugin-softcams-remy-openatv-softcampanel_V2.1_all.ipk
opkg install --force-reinstall /tmp/enigma2-plugin-softcams-remy-openatv-softcampanel_V2.1_all.ipk
sleep 1
rm -rf /tmp/enigma2-plugin-softcams-remy-openatv-softcampanel_V2.1_all.ipk > /dev/null
sleep 1
curl https://github.com/PrivateTr/Zone_enigma/raw/master/SK -Lko /etc/tuxbox/config/SoftCam.Key
/usr/bin/oscam -b -c /etc/tuxbox/config
killall -9 enigma2