#!/bin/sh
opkg remove enigma2-plugin-softcams-remy-softcamapp-mips-fhd
rm -rf /usr/camscript > /dev/null
sleep 1
curl https://download846.mediafire.com/jrx5vwyw6tvg/mml22hd5je9urzn/enigma2-plugin-softcams-remy-softcamapp-mips-fhd_V1.0_all.ipk -Lko /tmp/enigma2-plugin-softcams-remy-softcamapp-mips-fhd_V1.0_all.ipk
sleep 1
opkg --force-overwrite install /tmp/enigma2-plugin-softcams-remy-softcamapp-mips-fhd_V1.0_all.ipk
opkg install --force-reinstall /tmp/enigma2-plugin-softcams-remy-softcamapp-mips-fhd_V1.0_all.ipk
rm -rf /tmp/enigma2-plugin-softcams-remy-softcamapp-mips-fhd_V1.0_all.ipk > /dev/null
sleep 1
curl https://github.com/PrivateTr/remyteam_5.2/raw/master/SoftCam.Key -Lko /etc/tuxbox/config/SoftCam.Key
/usr/bin/oscam  -b -c /etc/tuxbox/config
echo  'YouTube KANALIMA ABONE OLARAK TAKIP EDEBILIRSINIZ'
echo  'https://www.youtube.com/c/ReMyTr'
sleep 2
killall -9 enigma2
