#!/bin/sh
curl https://download2267.mediafire.com/xo4lghekl5pg/1oqwho0ejzulyqt/enigma2-plugin-skins-prizma-mod_4.0_all.ipk -Lko /tmp/enigma2-plugin-skins-prizma-mod_4.0_all.ipk
opkg --force-overwrite install /tmp/enigma2-plugin-skins-prizma-mod_4.0_all.ipk
opkg install --force-reinstall /tmp/enigma2-plugin-skins-prizma-mod_4.0_all.ipk
echo  'YouTube KANALIMA ABONE OLARAK TAKIP EDEBILIRSINIZ'
echo  'https://www.youtube.com/c/ReMyTr'
sleep 2
killall -9 enigma2